mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^log/(?P<pseudo>\w+)/$', views.index_log, name='index_log'),
    url(r'^log/(?P<pseudo>\w+)/send/$', views.send, name='send'),
    url(r'^log/(?P<pseudo>\w+)/delete/(?P<notice_id>\d+)/$', views.delete, name='delete'),
    url(r'^log/(?P<pseudo>\w+)/change_notice/(?P<notice_id>\d+)/$', views.change_notice, name='change_notice'),
    url(r'^log/(?P<pseudo>\w+)/change_now/(?P<notice_id>\d+)/$', views.change_now, name='change_now'),
    url(r'^login/$', views.login, name='login'),
    url(r'^login/try/$', views.login_try, name='login_try'),
    url(r'^register/$', views.register, name='register'),
    url(r'^register/try/$', views.register_try, name='register_try'),
]

polls/models.py
from django.db import models


class Notice(models.Model):
    notice_title = models.CharField(max_length=100)
    notice_text = models.CharField(max_length=500)
    post_pseudo = models.CharField(max_length=50)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.notice_title

class User(models.Model):
    pseudo = models.CharField(max_length=50)
    password = models.CharField(max_length=50)
    def __str__(self):
        return self.pseudo

# Create your models here.

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from datetime import datetime

from .models import Notice, User

password = None

#home_page

def index(request):
    global password
    password = None
    all_notice = Notice.objects.order_by('-pub_date')
    context = {
        'all_notice': all_notice,
    }
    return render(request, 'polls/index.html', context)

#home_page connect

def index_log(request, pseudo):
    user = get_object_or_404(User, pseudo=pseudo)
    global password
    if password == "login":
        password = user.password
    if password != user.password:
        return HttpResponseRedirect(reverse('polls:index'))
    all_notice = Notice.objects.order_by('-pub_date')
    context = {
        'all_notice': all_notice,
        'pseudo': pseudo,
    }
    return render(request, 'polls/index_log.html', context)

#add a new notice when connected

def send(request, pseudo):
    if request.POST['title'] == "" or request.POST['text'] == "":
        return HttpResponseRedirect(reverse('polls:index_log', args=(), kwargs={'pseudo': pseudo}))
    notice = Notice(
        notice_title=request.POST['title'],
        notice_text=request.POST['text'],
        post_pseudo=pseudo,
        pub_date=datetime.now()
    )
    notice.save()
    return HttpResponseRedirect(reverse('polls:index_log', args=(), kwargs={'pseudo': pseudo}))

#delete a notice when connected

def delete(request, pseudo, notice_id):
    notice = get_object_or_404(Notice, pk=notice_id)
    notice.delete()
    return HttpResponseRedirect(reverse('polls:index_log', args=(), kwargs={'pseudo': pseudo}))

#modify a notice when connected

def change_notice(request, pseudo, notice_id):
    notice = get_object_or_404(Notice, pk=notice_id)
    if notice.post_pseudo != pseudo:
        return HttpResponseRedirect(reverse('polls:index_log', args=(), kwargs={'pseudo': pseudo}))
    context = {
        'pseudo': pseudo,
        'notice': notice,
    }
    return render(request, 'polls/change_notice.html', context)

#modify in database

def change_now(request, pseudo, notice_id):
    if request.POST['title'] == "" or request.POST['text'] == "":
        return HttpResponseRedirect(reverse('polls:change_notice', args=(), kwargs={'pseudo': pseudo, 'notice_id': notice_id}))
    notice = get_object_or_404(Notice, pk=notice_id)
    notice.notice_title = request.POST['title']
    notice.notice_text = request.POST['text']
    notice.save()
    return HttpResponseRedirect(reverse('polls:index_log', args=(), kwargs={'pseudo': pseudo}))

#register an account

def register(request):
    return render(request, 'polls/register.html')

#set new account in database

def register_try(request):
    if request.POST['pseudo'] == "" or request.POST['password'] == "" or request.POST['password'] != request.POST['confirm_password']:
        return HttpResponseRedirect(reverse('polls:register'))
    user = User(
        pseudo=request.POST['pseudo'],
        password=request.POST['password'],
    )
    user.save()
    return HttpResponseRedirect(reverse('polls:register'))

#login an account

def login(request):
    return render(request, 'polls/login.html')

#check account to login

def login_try(request):
    if request.POST['pseudo'] == "" or request.POST['password'] == "":
        return HttpResponseRedirect(reverse('polls:login'))
    all_user = User.objects.order_by('id')
    num_page = 1
    for user in all_user:
        if request.POST['pseudo'] == user.pseudo and request.POST['password'] == user.password:
            global password
            password = "login"
            return HttpResponseRedirect(reverse('polls:index_log', args=(), kwargs={'pseudo': user.pseudo}))
    return render(request, 'polls/login.html')

polls/templates/polls/change_notice.html
<!DOCTYPE HTML>

<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
    <title>Golden Book</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'polls:index_log' pseudo%}">Golden Book</a>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'polls:index_log' pseudo %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'polls:index' %}">Logout</a>
          </li>
        </ul>
      </div>
    </nav>
    <br/>
    <div id="zone_log">
      <form action="{% url 'polls:change_now' pseudo notice.id %}" method="post">
	{% csrf_token %}
	<div id="zone_text" class="form-group">
          <label>Title</label>
          <input type="text" class="form-control" value="{{ notice.notice_title }}" placeholder="Enter title" name="title">
	</div>
	<div id="zone_text" class="form-group">
          <label>Contents</label>
          <textarea class="form-control" rows="10" placeholder="Enter contents" name="text">{{ notice.notice_text }}</textarea>
	</div>
	<button type="submit" class="btn btn-outline-secondary">Change Notice</button>
      </form>
    </div>
  </body>
</html>

polls/templates/polls/index.html
<!DOCTYPE HTML>

<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
    <title>Golden Book</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'polls:index' %}">Golden Book</a>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'polls:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'polls:login' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'polls:register' %}">Register</a>
          </li>
        </ul>
      </div>
    </nav>
    <br/>
    <div class="jumbotron" id="zone_index_info">
      <b> Look all notices ! </b><br/><br/>
      <a class="btn btn-outline-light" href="#notice">Click here</a><br/><br/>
      <p id="help"><i>Login you to modify or post new notices</i></p>
    </div>
    <br/>
    {% if all_notice %}
    <a name="notice"/>
    <ul>
      {% for notice in all_notice %}
      <div class="jumbotron" id="zone_look_notice">
        <p id="title_notice"><b>{{ notice.notice_title }}</b></p>
        <hr class="my-4">
        <p id="contains_notice"> {{ notice.notice_text }}</p>
        <hr class="my-4">
        <p id="user_notice"><i>Message left by <b>{{ notice.post_pseudo }}</b></i></p>
      </div>
      <br/><br/>
      {% endfor %}
    </ul>
    {% endif %}
  </body>
</html>

polls/templates/polls/index_log.html
<!DOCTYPE HTML>

<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
    <title>Golden Book</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'polls:index_log' pseudo %}">Golden Book</a>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'polls:index_log' pseudo %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'polls:index' %}">Logout</a>
          </li>
        </ul>
      </div>
    </nav>
    <br/>
    <div class="jumbotron" id="zone_info">
      <b> Enter your notice here ! </b>
    </div>
    <div id="zone_notice">
      <form action="{% url 'polls:send' pseudo %}" method="post">
	{% csrf_token %}
	<div id="zone_text" class="form-group">
          <label>Title</label>
          <input type="text" class="form-control" placeholder="Enter title" name="title">
	</div>
	<div id="zone_text" class="form-group">
          <label>Contents</label>
          <textarea class="form-control" rows="10" cols="10" placeholder="Enter contents" name="text"></textarea>
	</div>
	<button type="submit" class="btn btn-outline-secondary">Send</button>
      </form>
    </div>
    <br/>
    <a href="#notice" class="btn btn-light" id="button_ancre">Look all notices</a>
    <br/>
    <hr class="my-4" id="separate">
    <br/><br/><br/>
    <a name="notice"/>
    <div class="jumbotron" id="zone_info">
      <b> Look all notices here ! </b>
    </div>
    <br/>
    {% if all_notice %}
    <ul>
      {% for notice in all_notice %}
      <div class="jumbotron" id="zone_look_notice">
	<p id="title_notice"><b>{{ notice.notice_title }}</b></p>
	<hr class="my-4">
	<p id="contains_notice"> {{ notice.notice_text }}</p>
	<hr class="my-4">
	<p id="user_notice"><i>Message left by <b>{{ notice.post_pseudo }}</b></i></p>
	{% if notice.post_pseudo == pseudo %}
	<a href="{% url 'polls:change_notice' pseudo notice.id %}" class="btn btn-outline-info">Change Notice</a>
	<a href="{% url 'polls:delete' pseudo notice.id %}" class="btn btn-danger">Delete</a>
	<br/><br/>
	{% endif %}
      </div>
      <br/>
      {% endfor %}
    </ul>
    {% else %}
    <p>No polls are available.</p>
    {% endif %}
  </body>
</html>

polls/templates/polls/login.html
<!DOCTYPE HTML>

<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
    <title>Golden Book</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'polls:index' %}">Golden Book</a>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'polls:index' %}">Home</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'polls:login' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'polls:register' %}">Register</a>
          </li>
        </ul>
      </div>
    </nav>
    <br/>
    <div id="zone_log">
      <form action="{% url 'polls:login_try' %}" method="post">
	{% csrf_token %}
	<div id="zone_text" class="form-group">
	  <label>Pseudo</label>
	  <input type="text" class="form-control" placeholder="Enter your pseudo" name="pseudo">
	</div>
	<div id="zone_text" class="form-group">
	  <label>Password</label>
	  <input type="password" class="form-control" placeholder="Enter your password" name="password">
	</div>
	<button type="submit" class="btn btn-outline-secondary">Login</button>
      </form>
    </div>
  </body>
</html>

polls/templates/polls/register.html
<!DOCTYPE HTML>

<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
    <title>Golden Book</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'polls:index' %}">Golden Book</a>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'polls:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'polls:login' %}">Login</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'polls:register' %}">Register</a>
          </li>
        </ul>
      </div>
    </nav>
    <br/>
    <div id="zone_log">
      <form action="{% url 'polls:register_try' %}" method="post">
	{% csrf_token %}
	<div id="zone_text" class="form-group">
	  <label>Pseudo</label>
	  <input type="text" class="form-control" placeholder="Enter your pseudo" name="pseudo">
	</div>
	<div id="zone_text" class="form-group">
	  <label>Password</label>
	  <input type="password" class="form-control" placeholder="Enter your password" name="password">
	</div>
	<div id="zone_text" class="form-group">
	  <label>Confirm Password</label>
	  <input type="password" class="form-control" placeholder="Confirm your password" name="confirm_password">
	</div>
	<button type="submit" class="btn btn-outline-secondary">Register</button>
      </form>
    </div>
  </body>
</html>